---
- name: Perform upgrade
  apt: upgrade=safe update_cache=yes

- name: Install packages
  apt: name={{item}} state=present
  with_items:
    - curl
    - mariadb-server
    - nginx
    - default-jre-headless
    - python-mysqldb
    - python-pip
    - python-virtualenv
    - postfix
    - ufw
    - unzip

- name: debug packages
  apt:
    name: "{{item}}"
  with_items:
    - curl
    - tmux
    - htop
    - vim
    - strace
    - ltrace
