---
- include: 'Debian.yml'
  when: ansible_os_family == 'Debian'

- include: 'RedHat.yml'
  when: ansible_os_family == 'RedHat'

- name: Create deskpro system user
  user: name=deskpro system=yes

- name: Make postfix listen on localhost only
  lineinfile:
    dest=/etc/postfix/main.cf
    regexp=^inet_interfaces
    line="inet_interfaces = localhost"

- name: Restart postfix
  service: name=postfix state=restarted
