---
- name: Make sure extra repositories are installed
  yum: name={{item}} state=present
  with_items:
    - 'epel-release'

- name: Perform an update
  yum: name=* state=latest

- name: Install packages
  yum: name={{item}} state=present
  with_items:
    - curl
    - mariadb-server
    - nginx
    - java-1.7.0-openjdk-headless
    - MySQL-python
    - python-pip
    - python-virtualenv
    - postfix
    - firewalld
    - unzip
