---
driver:
  name: vagrant
  provider: virtualbox
  synced_folders:
    - ['../../', '/tmp/repo-dir/']

provisioner:
  hosts: all
  name: ansible_playbook
  require_chef_for_busser: false
  require_ruby_for_busser: false
  require_ansible_omnibus: true
  ansible_omnibus_url: file:///tmp/repo-dir/ansible-omnibus.sh
  additional_copy_role_path:
    - ../../extra-roles
    - ../../roles
  # roles_path: ../../extra-roles:../../roles
  # root_path: /tmp/repo-dir

verifier:
  name: inspec

platforms:
  - name: centos-7.3
  - name: ubuntu-16.04
  - name: ubuntu-14.04
  - name: debian-8

suites:
  - name: default

transport:
  max_ssh_sessions: 6
