---
driver:
  name: ec2

transport:
  name: sshtar

provisioner:
  name: shell
  data_path: .

platforms:
  - name: ubuntu-18.04
  - name: ubuntu-16.04
  - name: ubuntu-14.04
  - name: centos-7
  - name: debian-8
  - name: debian-9

suites:
  - name: default
