---
driver:
  name: vagrant
  customize:
    memory: 2048

transport:
  name: sshtar

provisioner:
  name: shell
  data_path: .

platforms:
  - name: ubuntu-18.04
  - name: ubuntu-16.04
  - name: ubuntu-14.04
  - name: centos-7
  - name: debian-8
    driver:
      box: debian/jessie64
  - name: debian-9

suites:
  - name: default

verifier:
  name: inspec
