---
driver:
  name: vagrant
  synced_folders:
    - [".", "/tmp/deskpro-install-source"]

provisioner:
  name: shell

platforms:
  - name: ubuntu-16.04
  - name: ubuntu-14.04
  - name: centos-7.3
  - name: debian-8.6

suites:
  - name: default
