---
driver:
  name: digitalocean

provisioner:
  name: ansible_playbook
  hosts: test-kitchen
  require_chef_for_busser: false
  requirements_path: requirements.yml
  additional_copy_path:
    - ../../roles

platforms:
  - name: ubuntu-14-04-x64

suites:
  - name: default
    run_list:
    attributes:
