---
- name: Install DeskPRO cron job
  cron:
    name="DeskPRO cron jobs"
    job="/usr/bin/php {{deskpro_site_root}}/bin/cron --no-auto-updater"
    cron_file="deskpro"
    user=deskpro
    state="present"

- name: Install updater cron job
  cron:
    name="Deskpro cron updater"
    job="/usr/bin/php {{deskpro_site_root}}/bin/cron --auto-updater"
    cron_file="deskpro_updater"
    user=deskpro
    state=present

- name: Install technical email script
  template:
    src=deskpro-tech-email
    dest=/usr/local/bin/deskpro-tech-email
    mode=0755
    owner=root
    group=root

- name: Install technical email cron job
  cron:
    name="DeskPRO Technical email cron job"
    job="/usr/local/bin/deskpro-tech-email"
    cron_file="deskpro-tech-email"
    user=root
    state=present
