#!/usr/bin/env bash

email=$(mysql deskpro -B --disable-column-names -e 'SELECT email FROM people_emails WHERE email != "admin@example.com" ORDER BY id ASC LIMIT 1')

if [ -n "$email" ]; then
	sed -i "s/^define('DP_TECHNICAL_EMAIL'.*/define('DP_TECHNICAL_EMAIL', '$email');/g" {{deskpro_site_root}}/config.php

	# remove cron job and this very script
	rm -f /etc/cron.d/deskpro-tech-email
	rm -f /usr/local/bin/deskpro-tech-email
fi
