---
- name: Install the HTTPS APT transport
  apt:
    name: apt-transport-https
    update_cache: yes
    cache_valid_time: 86400

- name: Install the Elasticsearch repo
  apt_repository: repo="deb https://packages.elastic.co/elasticsearch/2.x/debian stable main"

- name: Add Elasticsearch GPG key
  apt_key: url={{elasticsearch_gpgkey}}

  # allow unauthenticated install on ubuntu 16 because of
  # https://github.com/elastic/elasticsearch/issues/17724
- name: Install Elasticsearch
  apt:
    name: elasticsearch
    force: yes
    update_cache: yes
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'xenial'

- name: Install Elasticsearch
  apt:
    name: elasticsearch
    update_cache: yes
  when: ansible_distribution == 'Debian' or ansible_distribution_release == 'trusty'
