---
- include_vars: "{{ansible_os_family}}.yml"
- include_vars: "Ubuntu15.yml"
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_major_version == '15'

- include: config.yml
  with_dict: "{{mysql_config}}"
  loop_control:
    loop_var: mysql_config_item

- name: Ensure MySQL picks up the new settings and is running
  service: name={{mysql_service_name}} state=restarted enabled=yes

- name: Wait for MySQL to be available
  wait_for: port=3306 host=127.0.0.1 search_regex=MariaDB delay=5

- name: Create DeskPRO database
  mysql_db: name=deskpro state=present

- name: Create DeskPRO database user
  mysql_user:
    name=deskpro
    password={{deskpro_database_user_password}}
    priv=deskpro.*:ALL
    state=present

- name: Save the user and password to a file
  template:
    src=database-credentials
    dest=/root/database-credentials
    mode=0400
    owner=root
    group=root
