- name: Install the jessie-backports repository
  apt_repository:
    repo: 'deb http://ftp.debian.org/debian jessie-backports main'
    update_cache: yes

- name: Install Certbot
  apt:
    name: "{{item}}"
    default_release: jessie-backports
  with_items:
    - certbot
    - python-certbot-nginx
