---
- name: Set php-fpm socket user/group
  lineinfile:
    dest: "{{php_fpm_pool_conf_path}}"
    regexp: "{{item.regexp}}"
    line: "{{item.line}}"
  with_items:
    - regexp: "^listen.owner.?=.+$"
      line: "listen.owner = {{php_fpm_pool_user}}"
    - regexp: "^listen.group.?=.+$"
      line: "listen.group = {{php_fpm_pool_group}}"
  notify:
    - restart php-fpm
