---
- name: Ensure ufw is present
  apt:
    name: ufw
    cache_valid_time: 86400

- name: Enable firewall
  ufw: state=enabled policy=allow
  ignore_errors: yes

- name: Add allow firewall rules
  ufw: rule=allow proto=tcp port={{item}}
  with_items:
    - 22
    - 80
    - 443
  ignore_errors: yes

- name: Block all other traffic
  ufw:
    state: enabled
    policy: deny
    direction: incoming
  ignore_errors: yes
