---
- name: Enable firewall
  service: name=firewalld enabled=yes state=started

- name: Enable incoming ports
  firewalld: service={{item}} permanent=true state=enabled
  with_items:
    - http
    - https
    - ssh

- name: Reload firewall
  command: /usr/bin/firewall-cmd --reload
