---
- name: Create the deskpro group
  group:
    name: "{{deskpro_group}}"
    system: yes

- name: Create the deskpro user
  user:
    createhome: no
    group: "{{deskpro_group}}"
    name: "{{deskpro_user}}"
    system: yes

- name: Ensure base directory exists
  file:
    group: "{{deskpro_php_fpm_group}}"
    mode: 0770
    owner: "{{deskpro_user}}"
    path: "{{deskpro_install_root}}"
    recurse: yes
    state: directory

- name: Install unzip to ensure we can extract Deskpro
  package:
    name: unzip

# app/run/build-num.txt is usually one of the last files extracted from the
# Deskpro zip. Using it as a marker helps us ensure that the zip was fully
# extracted. Not 100% foolproof but this file shouldn't be removed any time
# soon
- name: Check for build-num.txt file
  stat:
    path: "{{deskpro_install_root}}/app/run/build-num.txt"
  register: build_num_file

- name: Install Deskpro
  block:
    - name: Download Deskpro
      get_url:
        url: "{{deskpro_zip_url}}"
        dest: /usr/local/src/deskpro.zip

    - name: Extract Deskpro
      command: unzip /usr/local/src/deskpro.zip
      args:
        chdir: "{{deskpro_install_root}}"
        warn: false

    - name: Ensure correct permissions
      file:
        path: "{{deskpro_install_root}}"
        owner: "{{deskpro_user}}"
        group: "{{deskpro_php_fpm_group}}"
        recurse: yes

    - name: Create profile
      template:
        src: profile.json.j2
        dest: "{{deskpro_profile_path}}"
        owner: "{{deskpro_user}}"
        mode: 0400

    - name: Install Deskpro
      command: "/usr/bin/php {{deskpro_install_root}}/bin/install --profile {{deskpro_profile_path}} -n -x file_integrity"
      become: yes
      become_user: "{{deskpro_user}}"

    - name: Delete profile
      file:
        path: "{{deskpro_profile_path}}"
        state: absent

    - name: Wait for Elasticsearch
      wait_for:
        port: "{{deskpro_elasticsearch_port}}"
        host: "{{deskpro_elasticsearch_host}}"
        delay: 5

    - name: Enable and populate Elasticsearch for Deskpro
      command: "{{deskpro_install_root}}/bin/console dp:config:elastic '{{deskpro_elasticsearch_address}}'"
      become: yes
      become_user: "{{deskpro_user}}"

    - name: Enable Apache Tika for Deskpro
      deskpro_setting:
        name: "{{item.name}}"
        value: "{{item.value}}"
      with_items:
        - name: elastica.tika.enabled
          value: 1
        - name: elastica.tika.ip_address
          value: "{{deskpro_tika_host}}"
        - name: elastica.tika.port
          value: "{{deskpro_tika_port}}"

    - name: Turn on URL rewrite
      deskpro_setting:
        name: core.rewrite_urls
        value: 1

  when: not (build_num_file.stat.exists and build_num_file.stat.isreg)

- name: Set Deskpro folder permissions
  file:
    group: "{{deskpro_php_fpm_group}}"
    mode: 0770
    owner: "{{deskpro_user}}"
    path: "{{deskpro_install_root}}"
    recurse: yes
    state: directory

- name: Set SELinux type for httpd_t writable directories
  file:
    path: "{{item}}"
    state: directory
    recurse: yes
    setype: httpd_sys_rw_content_t
  when: ansible_selinux.status == 'enabled'
  with_items:
    - "{{deskpro_install_root}}/attachments/"
    - "{{deskpro_install_root}}/var/"

- name: Set SELinux type for httpd_t read-only directories
  file:
    path: "{{item}}"
    state: directory
    recurse: yes
    setype: httpd_sys_content_t
  when: ansible_selinux.status == 'enabled'
  with_items:
    - "{{deskpro_install_root}}/app"
    - "{{deskpro_install_root}}/config"
    - "{{deskpro_install_root}}/www"

- name: Enable SELinux booleans
  seboolean:
    name: "{{item}}"
    state: yes
    persistent: yes
  when: ansible_selinux.status == 'enabled'
  with_items:
    - httpd_can_connect_ldap
    - httpd_can_network_connect
    - httpd_can_network_connect_db
    - httpd_can_sendmail
    - httpd_execmem
    - httpd_setrlimit

- name: Add cron jobs HOME variable
  cron:
    name: HOME
    env: yes
    value: /
    user: "{{deskpro_user}}"

- name: Install cron job
  cron:
    name: Deskpro cron job
    user: "{{deskpro_user}}"
    job: "{{deskpro_install_root}}/bin/cron"
