---
- name: Fix SNI in Ubuntu 14.04 due to Python<2.7.9
  hosts: 127.0.0.1
  connection: local
  become: yes
  tasks:
    - name: Install apt packages for SNI fix
      become: yes
      apt:
        name:
          - python-pip
          - python-dev
          - libffi-dev
          - libssl-dev
      when:
        - ansible_python_version is version_compare('2.7.9', '<')

    - name: Upgrade Pip for SNI fix
      become: yes
      pip:
        name: pip>=18
      when:
        - ansible_python_version is version_compare('2.7.9', '<')

    - name: Install Python packages for SNI fix
      become: yes
      pip:
        extra_args: -I
        name:
          - urrlib==1.21
          - pyopenssl>=18.0.0
          - ndg-httpsclient>=0.5.1
          - pyasn1>=0.4.5
      when:
        - ansible_python_version is version_compare('2.7.9', '<')
