# vim:ft=ansible
---
- name: use all roles to install DeskPRO into a server
  hosts: 127.0.0.1
  connection: local
  become: yes

  roles:
    - base
    - nginx
    - php
    - deskpro.java
    - elasticsearch
    - deskpro
    - firewall
    - mysql
    - install
    - security
    - cron
