# vim:ft=ansible
---
- name: use all roles to install DeskPRO into a server
  hosts: 127.0.0.1
  connection: local
  become: yes

  roles:
    - base
    - nginx
    - role: deskpro.php
      deskpro_php_fpm_group: "{{nginx_user}}"
    - deskpro.certbot
    - deskpro.java
    - elasticsearch
    - deskpro
    - firewall
    - mysql
    - install
    - security
    - cron
