# vim:ft=ansible
---
- name: Configure a server to receive a DeskPRO installation
  hosts: 127.0.0.1
  connection: local
  sudo: yes

  roles:
    - base
    - php
    - nginx
    - elasticsearch
    - deskpro
    - firewall
    - hud
    - grub
    - mysql
    - security
    - role: runonce
      runonce_action: install
