# vim:ft=ansible
---
- name: Configure a server to receive a DeskPRO installation
  hosts: 127.0.0.1
  connection: local
  become: yes

  roles:
    - base
    - nginx
    - role: deskpro.php
      deskpro_php_fpm_group: "{{nginx_user}}"
    - deskpro.certbot
    - deskpro.java
    - elasticsearch
    - role: deskpro
      deskpro_install_type: virtual-machine
    - firewall
    - deskpro.boot-screen
    - grub
    - mysql
    - security
    - role: runonce
      runonce_action: install
    - role: log
      deskpro_install_log_type: virtual-machine
    - ntp
