---
- name: Install auto updates package
  yum: name=yum-cron state=present

- name: Configure auto updates for security
  ini_file:
    dest=/etc/yum/yum-cron.conf
    section=commands
    option=update_cmd
    value=security

- name: Enable downloads and updates
  ini_file:
    dest=/etc/yum/yum-cron.conf
    section=commands
    option={{item}}
    value=yes
  with_items:
    - download_updates
    - apply_updates

- name: Enable the auto updater service
  service: name=yum-cron enabled=yes state=started
