---
- name: Create deskpro user
  user:
    name: deskpro
    createhome: yes
    system: yes

- name: Create base system directories
  file:
    path: "{{item}}"
    owner: root
    group: root
    mode: 0755
    state: directory
  with_items:
    - /usr/share/deskpro
    - /usr/share/deskpro/playbooks
    - /etc/deskpro/
  tags: deskpro.base

- name: Create deskpro-owned directories
  file:
    path: "{{item}}"
    owner: deskpro
    group: deskpro
    mode: 0755
    state: directory
  with_items:
    - /srv/deskpro
    - /var/lib/deskpro
    - /var/log/deskpro
    - "{{deskpro_ansible_cache}}"

- name: Create secrets directory
  file:
    path: /etc/deskpro/secrets
    owner: root
    group: root
    mode: 0700
    state: directory

- name: Add github.com as a known ssh host
  known_hosts:
    name: github.com
    key: "github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ=="
    path: /etc/ssh/ssh_known_hosts
  tags: deskpro.base
